/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.database;

import static com.mycompany.database.Tacgia.conn;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class NhaXuatBan extends javax.swing.JFrame {

    /**
     * Creates new form NhaXuatBan
     */
    static Connection conn;

    public NhaXuatBan() {
        initComponents();
        loadDB();
    }

    public Date checkNgay(String ngay) throws ParseException {
        String regex = "([12]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]))";
        Pattern p = Pattern.compile(regex);
        Matcher m = p.matcher(ngay);
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Nhập ngày tháng lỗi! Mời nhập lại");
            return null;
        }
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        java.sql.Date nxb = java.sql.Date.valueOf(format.format(format.parse(ngay)));
        return nxb;
    }

    public String checkDT(String dt) {
        String regex = "^(\\+84|0)[0-9]{9}$";
        Pattern p = Pattern.compile(regex);
        Matcher m = p.matcher(dt);
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Nhập số điện thoại lỗi! Mời nhập lại");
            return null;
        }
        return dt;
    }

    public String checkMail(String mail) {
        String regex = "^[a-zA-Z][\\w-]+@([\\w]+\\.[\\w]+|[\\w]+\\.[\\w]{2,}\\.[\\w]{2,}$)";
        Pattern p = Pattern.compile(regex);
        Matcher m = p.matcher(mail);
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Nhập email lỗi! Mời nhập lại");
            return null;
        }
        return mail;
    }

    private boolean checkKey(String mxb) {
        boolean kq = false;
        try {
            conn = Database.connect();
            String sql = "SELECT * FROM `nxb` Where mxb = ('" + mxb + "') ";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                kq = true;
            }
            conn.close();
        } catch (ClassNotFoundException | SQLException e) {
        }
        return kq;
    }

    public void loadDB() {
        try {
            conn = Database.connect();
            tbNxb.removeAll();
            String sql = "SELECT * FROM `nxb`";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            String[] arr = {"MXB", "TNXB", "NXB", "ĐT", "Email", "ĐC", "GC"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);

            while (rs.next()) {
                Vector<String> vt = new Vector<>();
                vt.add(rs.getString("mxb"));
                vt.add(rs.getString("tnxb"));
                vt.add(rs.getString("nxb"));
                vt.add(rs.getString("dt"));
                vt.add(rs.getString("em"));
                vt.add(rs.getString("dc"));
                vt.add(rs.getString("gc"));
                model.addRow(vt);
                System.out.println(vt);
            }
            tbNxb.setModel(model);
            conn.close();
        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EdtMxb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EdtTnxb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EdtDt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EdtEm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EdtDc = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        EdtGc = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        EdtNxb = new javax.swing.JTextField();
        BtnThem = new javax.swing.JButton();
        BtnSua = new javax.swing.JButton();
        BtnXoa = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbNxb = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tkBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mxb:");

        EdtMxb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên:");

        EdtTnxb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Điện Thoại:");

        EdtDt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email: ");

        EdtEm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EdtEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtEmActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ: ");

        EdtDc.setColumns(20);
        EdtDc.setRows(5);
        jScrollPane2.setViewportView(EdtDc);

        EdtGc.setColumns(20);
        EdtGc.setRows(5);
        jScrollPane1.setViewportView(EdtGc);

        jLabel1.setText("Ghi Chú: ");

        EdtNxb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EdtDt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EdtTnxb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EdtMxb)
                    .addComponent(EdtEm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(EdtNxb))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EdtMxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EdtTnxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EdtNxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EdtEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnThem.setText("Thêm");
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });

        BtnSua.setText("Sửa");
        BtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaActionPerformed(evt);
            }
        });

        BtnXoa.setText("Xóa");
        BtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaActionPerformed(evt);
            }
        });

        tbNxb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNxb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNxbMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbNxb);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NXB");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tkBtn.setText("Tìm Kiếm");
        tkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnThem)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSua)
                        .addGap(18, 18, 18)
                        .addComponent(BtnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(tkBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThem)
                    .addComponent(BtnSua)
                    .addComponent(BtnXoa)
                    .addComponent(tkBtn))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuaActionPerformed
        // TODO add your handling code here:
        try {
            String mxb = EdtMxb.getText().trim();
            String tnxb = EdtTnxb.getText().trim();
            String nxb = EdtNxb.getText().trim();
            if (checkNgay(nxb) == null) {
                return;
            }
            String dt = EdtDt.getText().trim();
            if (checkDT(dt) == null) {
                return;
            }
            String em = EdtEm.getText().trim();
            if (checkMail(em) == null) {
                return;
            }
            String dc = EdtDc.getText().trim();
            String gc = EdtGc.getText().trim();
            String sql = "Update nxb Set tnxb = (N'" + tnxb + "'), nxb = ('" + nxb + "'), dt = ('" + dt + "'), em = ('"
                    + em + "'), dc = ('" + dc + "'), gc = ('" + gc + "') Where mxb = ('" + mxb + "')";
            conn = Database.connect();
            Statement st = conn.createStatement();
            st.executeUpdate(sql);
            st.close();
            conn.close();
            loadDB();
//            loadJCB();
        } catch (HeadlessException | ClassNotFoundException | SQLException | ParseException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_BtnSuaActionPerformed

    private void tbNxbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNxbMouseClicked
        // TODO add your handling code here:
        int i = tbNxb.getSelectedRow();
        DefaultTableModel tb = (DefaultTableModel) tbNxb.getModel();
        EdtMxb.setText(tb.getValueAt(i, 0).toString());
        EdtTnxb.setText(tb.getValueAt(i, 1).toString());
        EdtNxb.setText(tb.getValueAt(i, 2).toString());
        EdtDt.setText(tb.getValueAt(i, 3).toString());
        EdtEm.setText(tb.getValueAt(i, 4).toString());
        EdtDc.setText(tb.getValueAt(i, 5).toString());
        EdtGc.setText(tb.getValueAt(i, 6).toString());

    }//GEN-LAST:event_tbNxbMouseClicked

    private void BtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaActionPerformed
        // TODO add your handling code here:
        try {
            String mxb = EdtMxb.getText().trim();
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc chắn muốn xóa nhà xuát bản với mã " + mxb + "?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String sql = "Delete From nxb Where mxb = ('" + mxb + "')";
                conn = Database.connect();
                Statement st = conn.createStatement();
                st.executeUpdate(sql);
                st.close();
                conn.close();
                loadDB();
//                loadJCB();
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_BtnXoaActionPerformed

    private void tkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkBtnActionPerformed
        try {
            // TODO add your handling code here:
            tbNxb.removeAll();
            String mxb = EdtMxb.getText().trim();
            String tnxb = EdtTnxb.getText().trim();
            String nxb = EdtNxb.getText().trim();
            conn = Database.connect();
            String sql = "SELECT * FROM `nxb` Where mxb like '%" + mxb + "%' and tnxb like N'%" + tnxb + "%' and nxb like '%" + nxb + "%' ";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            String[] arr = {"MXB", "TNXB", "NXB", "ĐT", "Email", "ĐC", "GC"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);

            while (rs.next()) {
                Vector<String> vt = new Vector<>();
                vt.add(rs.getString("mxb"));
                vt.add(rs.getString("tnxb"));
                vt.add(rs.getString("nxb"));
                vt.add(rs.getString("dt"));
                vt.add(rs.getString("em"));
                vt.add(rs.getString("dc"));
                vt.add(rs.getString("gc"));
                model.addRow(vt);
                System.out.println(vt);
            }
            tbNxb.setModel(model);
            conn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(NhaXuatBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tkBtnActionPerformed

    private void EdtEmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EdtEmActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_EdtEmActionPerformed

    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnThemActionPerformed
        // TODO add your handling code here:
        try {
            String mxb = EdtMxb.getText().trim();
            if (!checkKey(mxb)) {
                JOptionPane.showMessageDialog(this, "Lỗi trùng nhà xuất bản! Mời nhập lại");
                return;
            }
            String tnxb = EdtTnxb.getText().trim();
            String nxb = EdtNxb.getText().trim();
            if (checkNgay(nxb) == null) {
                return;
            }
            String dt = EdtDt.getText().trim();
            if (checkDT(dt) == null) {
                return;
            }
            String em = EdtEm.getText().trim();
            if (checkMail(em) == null) {
                return;
            }
            String dc = EdtDc.getText().trim();
            String gc = EdtGc.getText().trim();
            String sql = "Insert nxb Values('" + mxb + "',N'" + tnxb + "','" + nxb + "','" + dt + "','" + em + "','"
                    + dc + "','" + gc + "')";
            conn = Database.connect();
            try (Statement st = conn.createStatement()) {
                st.executeUpdate(sql);
            }
            conn.close();
            // loadJCB();
            loadDB();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (ParseException ex) {
            Logger.getLogger(NhaXuatBan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }// GEN-LAST:event_BtnThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhaXuatBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnXoa;
    private javax.swing.JTextArea EdtDc;
    private javax.swing.JTextField EdtDt;
    private javax.swing.JTextField EdtEm;
    private javax.swing.JTextArea EdtGc;
    private javax.swing.JTextField EdtMxb;
    private javax.swing.JTextField EdtNxb;
    private javax.swing.JTextField EdtTnxb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbNxb;
    private javax.swing.JButton tkBtn;
    // End of variables declaration//GEN-END:variables
}
