/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.database;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Tacgia extends javax.swing.JFrame {

    /**
     * Creates new form Tacgia
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public Tacgia() throws ClassNotFoundException, SQLException {
        initComponents();
        LoadDB();
        loadJCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EdtMtg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EdtHvt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EdtGt = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        EdtDt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EdtEm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EdtDc = new javax.swing.JTextArea();
        BtnThem = new javax.swing.JButton();
        EdtNs = new com.toedter.calendar.JDateChooser();
        BtnSua = new javax.swing.JButton();
        BtnXoa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbTTG = new javax.swing.JTable();
        jCbTacGia = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        EdtSo = new javax.swing.JTextField();
        BtnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TTG Shop");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("MTG: ");

        EdtMtg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ và tên: ");

        EdtHvt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày Sinh:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Giới Tính:");

        EdtGt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn giới tính--", "Nam", "Nữ" }));
        EdtGt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtGtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Điện Thoại:");

        EdtDt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email: ");

        EdtEm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EdtEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtEmActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Địa chỉ: ");

        EdtDc.setColumns(20);
        EdtDc.setRows(5);
        jScrollPane2.setViewportView(EdtDc);

        BtnThem.setText("Thêm");
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });

        BtnSua.setText("Sửa");
        BtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaActionPerformed(evt);
            }
        });

        BtnXoa.setText("Xóa");
        BtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaActionPerformed(evt);
            }
        });

        jButton2.setText("Xuất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EdtDt)
                            .addComponent(EdtGt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EdtNs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EdtHvt)
                            .addComponent(EdtMtg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EdtEm)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnThem)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSua)
                        .addGap(18, 18, 18)
                        .addComponent(BtnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EdtMtg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EdtHvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(EdtNs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(EdtGt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdtDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EdtEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThem)
                    .addComponent(BtnSua)
                    .addComponent(BtnXoa)
                    .addComponent(jButton2)))
        );

        TbTTG.setFont(new java.awt.Font("JetBrainsMono NF", 0, 14)); // NOI18N
        TbTTG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbTTG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbTTGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbTTG);

        jCbTacGia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbTacGiaItemStateChanged(evt);
            }
        });
        jCbTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTacGiaActionPerformed(evt);
            }
        });

        jLabel9.setText("Tác Giả");

        EdtSo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EdtSoKeyReleased(evt);
            }
        });

        BtnTimKiem.setText("Tìm Kiếm");
        BtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(BtnTimKiem)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EdtSo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbTacGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCbTacGia)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnTimKiem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EdtSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean CheckKey(String mtg) {
        boolean kq = false;
        try {
            conn = Database.connect();
            String sql = "SELECT * FROM `tacgia` Where mtg = ('" + mtg + "') ";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (!rs.next()) {
                kq = true;
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return kq;
    }

    private void loadJCB() {
        try {
            jCbTacGia.removeAllItems();
            conn = Database.connect();
            String sql = "SELECT * FROM `tacgia`";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                jCbTacGia.addItem(rs.getNString("ttg"));
                mp.put(rs.getNString("ttg"), rs.getNString("mtg"));

            }
            st.close();
            conn.close();
        } catch (Exception e) {
        }
    }
    private void EdtSoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdtSoKeyReleased
        // TODO add your handling code here:
        if (!((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyChar() == (char) 8)) {
            JOptionPane.showMessageDialog(this, "Nhap sai");
            String a = EdtSo.getText();
            EdtSo.setText(a.substring(0, a.length() - 1));
        }
    }//GEN-LAST:event_EdtSoKeyReleased

    private void BtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTimKiemActionPerformed
        // TODO add your handling code here:
        try {
            TbTTG.removeAll();
            String mtg = EdtMtg.getText().trim();
            String ttg = EdtHvt.getText().trim();
            String gt = EdtGt.getSelectedItem().toString();
            if (gt.equals("--Chọn giới tính--")) {
                gt = "";
            }
            conn = Database.connect();
            String sql = "SELECT * FROM `tacgia` Where mtg like '%" + mtg + "%' and ttg like N'%" + ttg + "%' and gt like N'%" + gt + "%' ";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            String[] arr = {"MTG", "TTG", "NS", "GT", "ĐT", "Email", "ĐC"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);

            while (rs.next()) {
                Vector<String> vt = new Vector<>();
                vt.add(rs.getString("mtg"));
                vt.add(rs.getString("ttg"));
                vt.add(rs.getString("ns"));
                vt.add(rs.getString("gt"));
                vt.add(rs.getString("dt"));
                vt.add(rs.getString("mail"));
                vt.add(rs.getString("dc"));
                model.addRow(vt);
                System.out.println(vt);
            }
            TbTTG.setModel(model);
            conn.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BtnTimKiemActionPerformed

    private void jCbTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbTacGiaActionPerformed

    private void jCbTacGiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbTacGiaItemStateChanged
        // TODO add your handling code here:
        String ttg = jCbTacGia.getSelectedItem().toString();
        String mtg = mp.get(ttg);
//        EdtHvt.setText(ttg);
    }//GEN-LAST:event_jCbTacGiaItemStateChanged

    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnThemActionPerformed
        // TODO add your handling code here:
        try {
            String mtg = EdtMtg.getText().trim();
            String ttg = EdtHvt.getText().trim();
            Date ns = new Date(EdtNs.getDate().getTime());
            String gt = EdtGt.getSelectedItem().toString();
            String dt = EdtDt.getText().trim();
            String mail = EdtEm.getText().trim();
            String dc = EdtDc.getText().trim();
            String sql = "Insert tacgia Values('" + mtg + "',N'" + ttg + "','" + ns + "','" + gt + "','" + dt + "','"
                    + mail + "','" + dc + "')";
            if (!CheckKey(mtg)) {
                JOptionPane.showMessageDialog(this, "Loi trung Ma tac gia");
                return;
            }
            conn = Database.connect();
            try (Statement st = conn.createStatement()) {
                st.executeUpdate(sql);
            }
            conn.close();
            loadJCB();
            LoadDB();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }// GEN-LAST:event_BtnThemActionPerformed

    private void EdtEmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EdtEmActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_EdtEmActionPerformed

    private void EdtGtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EdtGtActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_EdtGtActionPerformed

    private void BtnSuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnSuaActionPerformed
        // TODO add your handling code here:
        try {
            String mtg = EdtMtg.getText().trim();
            String ttg = EdtHvt.getText().trim();
            Date ns = new Date(EdtNs.getDate().getTime());
            String gt = EdtGt.getSelectedItem().toString();
            String dt = EdtDt.getText().trim();
            String mail = EdtEm.getText();
            String dc = EdtDc.getText().trim();
            String sql = "Update tacgia Set ttg = (N'" + ttg + "'), ns = ('" + ns + "'), gt = ('" + gt + "'), dt = ('"
                    + dt + "'), mail = ('" + mail + "'), dc = ('" + dc + "') Where mtg = ('" + mtg + "')";
            conn = Database.connect();
            Statement st = conn.createStatement();
            st.executeUpdate(sql);
            st.close();
            conn.close();
            LoadDB();
            loadJCB();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }// GEN-LAST:event_BtnSuaActionPerformed

    private void BtnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnXoaActionPerformed
        // TODO add your handling code here:
        try {
            String mtg = EdtMtg.getText().trim();
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc chắn muốn xóa tác giả với mã " + mtg + "?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String sql = "Delete From tacgia Where mtg = ('" + mtg + "')";
                conn = Database.connect();
                Statement st = conn.createStatement();
                st.executeUpdate(sql);
                st.close();
                conn.close();
                LoadDB();
                loadJCB();
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }// GEN-LAST:event_BtnXoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton2ActionPerformed

    private void TbTTGMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TbTTGMouseClicked
        // TODO add your handling code here:
        int i = TbTTG.getSelectedRow();
        DefaultTableModel tb = (DefaultTableModel) TbTTG.getModel();
        EdtMtg.setText(tb.getValueAt(i, 0).toString());
        EdtHvt.setText(tb.getValueAt(i, 1).toString());
        String ngay = tb.getValueAt(i, 2).toString();
        java.util.Date ns;
        try {
            ns = new SimpleDateFormat("yyyy-MM-dd").parse(ngay);
            EdtNs.setDate(ns);
        } catch (Exception e) {
        }
        EdtGt.setSelectedItem(tb.getValueAt(i, 3).toString());
        EdtDt.setText(tb.getValueAt(i, 4).toString());
        EdtEm.setText(tb.getValueAt(i, 5).toString());
        EdtDc.setText(tb.getValueAt(i, 6).toString());
    }// GEN-LAST:event_TbTTGMouseClicked

    static Connection conn = null;
    static Map<String, String> mp = new HashMap<>();

    public void LoadDB() throws ClassNotFoundException, SQLException {
        conn = Database.connect();
        TbTTG.removeAll();

        String sql = "SELECT * FROM `tacgia`";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        String[] arr = {"MTG", "TTG", "NS", "GT", "ĐT", "Email", "ĐC"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);

        while (rs.next()) {
            Vector<String> vt = new Vector<>();
            vt.add(rs.getString("mtg"));
            vt.add(rs.getString("ttg"));
            vt.add(rs.getString("ns"));
            vt.add(rs.getString("gt"));
            vt.add(rs.getString("dt"));
            vt.add(rs.getString("mail"));
            vt.add(rs.getString("dc"));
            model.addRow(vt);
            System.out.println(vt);
        }
        TbTTG.setModel(model);
        conn.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tacgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tacgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tacgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tacgia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Tacgia().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(Tacgia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnTimKiem;
    private javax.swing.JButton BtnXoa;
    private javax.swing.JTextArea EdtDc;
    private javax.swing.JTextField EdtDt;
    private javax.swing.JTextField EdtEm;
    private javax.swing.JComboBox<String> EdtGt;
    private javax.swing.JTextField EdtHvt;
    private javax.swing.JTextField EdtMtg;
    private com.toedter.calendar.JDateChooser EdtNs;
    private javax.swing.JTextField EdtSo;
    private javax.swing.JTable TbTTG;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCbTacGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
